"""add userdb-conmm2

Revision ID: 0e25643c1a98
Revises: def4178d2f6a
Create Date: 2023-08-16 21:18:37.661079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e25643c1a98'
down_revision = 'def4178d2f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('touxian')
    with op.batch_alter_table('userdb', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'conmm', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdb', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('touxian',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('SQname', mysql.VARCHAR(length=6000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
