"""add userdb-conmm2

Revision ID: 7735d28f7082
Revises: 0e25643c1a98
Create Date: 2023-08-16 21:25:27.183067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7735d28f7082'
down_revision = '0e25643c1a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdb', schema=None) as batch_op:
        batch_op.drop_constraint('userdb_conmm__fk', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdb', schema=None) as batch_op:
        batch_op.create_foreign_key('userdb_conmm__fk', 'conmm', ['role'], ['id'])

    # ### end Alembic commands ###
