"""add Huo dong

Revision ID: ddcb382d2f3c
Revises: 1107b9d9dcf5
Create Date: 2023-08-16 19:39:28.267887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcb382d2f3c'
down_revision = '1107b9d9dcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('huodong',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sheqv', sa.Integer(), nullable=False),
    sa.Column('huodongname', sa.String(length=128), nullable=False),
    sa.Column('shujiang', sa.DateTime(), nullable=False),
    sa.Column('didian', sa.String(length=360), nullable=False),
    sa.Column('neirong', sa.String(length=3000), nullable=False),
    sa.Column('jieshuSJ', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('huodong')
    # ### end Alembic commands ###
