"""add conmm is touxian

Revision ID: def4178d2f6a
Revises: ddcb382d2f3c
Create Date: 2023-08-16 19:45:03.017519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def4178d2f6a'
down_revision = 'ddcb382d2f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conmm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SQname', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('touxian',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SQname', sa.String(length=6000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('touxian')
    op.drop_table('conmm')
    # ### end Alembic commands ###
